name: cooksy
description: "Cooksy is a cooking recipe app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.6
  firebase_core: ^3.6.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1
  flutter_svg: ^2.0.10+1
  firebase_auth: ^5.3.1
  dio: ^5.7.0
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  cloud_firestore: ^5.4.4
  image_picker: ^1.1.2
  firebase_storage: ^12.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/icons/app_icon.png
